### ISSUE TITLE
Github pages

### ISSUE THREAD

**Issue by BlackIQ** [sina-yeganeh/welcome-page#1]
Use Github-Pages to people can visit your project online.

Settings > Pages > [ Set branch and directory ]
After that project will be online via this link : https://sina-yeganeh.github.io/welcome-page

Any question, ask me!

Amir.

**Comment by sina-yeganeh** [comment]
sure, do you have discord?

**Comment by sina-yeganeh** [comment]
And how you are full time lover? :)))

**Comment by BlackIQ** [comment]
For Discord, yeah I have.
For full time lover, really have no idea 🤣 

Dicord: BlackIQ#3499
Telegram: https://t.me/BlackIQ

Contact me in Telegram. New Discord.

**Comment by sina-yeganeh** [comment]
I can't get into the telegram, becuse it need vpn :(

**Comment by BlackIQ** [comment]
Let's close this issue body.
